ANSIBLE_USER: kevin
git_dir: /home/{{ ANSIBLE_USER }}/{{ APPLICATION }}
APPLICATION: nerdperk
netbox_dns: netbox.thejfk.ca
certs_dir: "/opt/certs"
keepalived_conf: "keepalived.conf"
keepalived_dir: "/etc/keepalived/"
INTERFACE: eth0   
internal_vip: 192.168.80.9
external_vip: 192.168.80.38
internal_router: 171
dev_db: 192.168.80.51
prod_db: 192.168.80.61
external_router: 181
nfs_target_dir: /var/www/web/sites/default/files/
nfs_server: 192.168.11.20
nfs_share: /mnt/yes/gitbuilds/recursioncomic
