ANSIBLE_USER: kevin
git_dir: /home/{{ ANSIBLE_USER }}/{{ APPLICATION }}
APPLICATION: nerdperk
netbox_dns: netbox.thejfk.ca
INTERFACE: eth0   
internal_router: 171
dev_db: 192.168.80.50
prod_db: 192.168.80.60
external_router: 181
nfs_target_dir: /var/www/web/sites/default/files
nfs_server: 192.168.11.20
nfs_share: /mnt/yes/gitbuilds/{{ APPLICATION }}/files
dbName: "{{ APPLICATION }}"
username: "{{ APPLICATION }}"
drush: /var/www/vendor/drush/drush/drush