$ANSIBLE_VAULT;1.1;AES256
62303136366463346535663435633262353865343064383966376665316365326430316664323166
3061303834323032663732366461366162633665616530390a613062643364313062363632386235
62623263316565383239663464356266373630663932656236613238653464653831353537346234
3430396232333330610a386232313330653339636130356530316538383965663931333537376464
63623834616465663766393561656231363832633033323063373039626261386265633535376131
30623737663635393639333032393962353338303435396336333734323563666432663965356461
37373163353739633365643735653531623335383831306366303064393933636361313331366231
63313033616230633430393033393836646239323534636234326138616539373335383431303661
37343133326132313032366636306263663066333734373634643430313839613437303838613830
35393631373362366530336534313936323138636131396464306338373539666638333364366538
62616233393233373639363533386137666265393633333164363236306334333635656162333833
31386136373739663438653033363634626136373064363539353233306438616665343832656430
64303066383136353164306537303332306162336634363063326561656238653132393236646263
33633932343063373461633732396366656661623133383631393663313864653936376233383339
66356236323830653762666338653839616364306231393362386536643361613765383637626539
34333662613962633739
