$ANSIBLE_VAULT;1.1;AES256
66636563366532303634356130343639363532653533653039373131363439343238313134623237
3436623361633039613331366236363832626461653834610a366666303162666165363732656239
36373036383338346332386631663930396139386235356636363533663863313161643134643838
6232323336333536340a613330643161323539306636633962343838616638333635353662323164
63663061613838356535643332373261653738656236663565663738323931636534383161313536
32343864633833343039646536623061366630366662653633626131613766323037386661653466
61383766373230353561303534623063303432353635303638656363376533616331663463323337
34663536646336353036653335333634363936383462373730336533336565363366653664323139
32343735613233623538373033656539323632656632393137653663393838353034363731646631
30393437393930623665343734666562643861666661356437633464353037353333666137633931
31633032363662303539356436386634373363666364613664653766386663393664313037396162
30363430326434363434353162333533323366386235393665336462316332313331373830643162
30313236326162316364313665366238356635376630613563653634333362366565
