$ANSIBLE_VAULT;1.1;AES256
34316231376462326433396434393232303135313961666335373331663762343837633232633638
6532373761616630633238363161666138393933353839330a323663636634396233653266326230
36363137313939356664366337316430353535656164653236393562656162633334396263396330
3635623265316330300a386465633961613063396465383034623461373265316136613161613562
63393862346432633736313633316330383361623237656364623337396132353863333138353831
36313930303365643139653530643538663865396661623131366132613536316632393339393463
32653462643463396539613433343935383935353230383439633231316339343931633863346636
62656365383561353237656261663935333064343264316332643436343238323334346232363937
31633334303735656566303739316335643031303835333439313862356635306639353335636235
65343639393831356363663362343930356530653831373665323736326634343039643864373866
37636333313832303063353261353632316337316531393464363265323533643665653937333137
62373338343739363661393566303664633539336261316666663137393062346638666133623362
32643163373664303535323065326633623133353833383530383164373663633631
