$ANSIBLE_VAULT;1.1;AES256
30323565663233666134363333326639623866366530633964613933626662623761633639393337
6463363866333038643765633333373664313733316138300a663037373963633533353363386561
61623035356563646664306432303333386438383336346565383834613331663134386534363434
6337643166343437630a633332616165383937633636616561646434303161356563343331613464
31646436316235633732383062643230333337623030653638623131363266623966663765623938
65373439663532393132366564656234396266613830363230306463396537333238336166663962
31643132626636666338376465373736333063316133623231366466393761373434356135303131
35616532626533326561366336616362663761613732373536396233353635623432373139383964
61326362363839363032656238316531616366636337303934343535356433633932623935626262
34353066643035613561313232306134313963663133346136323532316432623463323635373662
66306330306430386664343439393332376565313532623561356631343335383138373939353533
62333831636262636339393862303737363431336464323834653565613339666564656163616437
61343337616136386134336337396538393762303566366162656562646364333735
